/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "checkpoint.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(checkpoint_header, checkpoint_header, AUTO)


PB_BIND(single_core_rvgc_rvv_rvh_memlayout, single_core_rvgc_rvv_rvh_memlayout, AUTO)



