#include "../instr/pseudo.h"
#include "../instr/compress.h"
#include "../instr/compute.h"
#include "../instr/control.h"
#include "../instr/ldst.h"
#include "../instr/muldiv.h"
#include "../instr/system.h"
#include "../instr/special.h"
