// Compatibility shims for GLIBCXX symbols > 3.4.19
// This allows the shared library built on Ubuntu 20.04 to run on CentOS 7
// which only has libstdc++ with GLIBCXX up to 3.4.19.

#ifdef _SHARE

#include <stdexcept>
#include <string>
#include <cstdarg>
#include <cstdio>

// GLIBCXX_3.4.20: __throw_out_of_range_fmt (GCC 5+)
// Provide our own implementation that only uses GLIBCXX_3.4 symbols.
namespace std {
void __throw_out_of_range_fmt(const char *fmt, ...)
    __attribute__((noreturn, weak));
void __throw_out_of_range_fmt(const char *fmt, ...) {
  char buf[256];
  va_list ap;
  va_start(ap, fmt);
  vsnprintf(buf, sizeof(buf), fmt, ap);
  va_end(ap);
  // Use std::string constructor to avoid out_of_range(const char*) which needs GLIBCXX_3.4.21
  throw std::out_of_range(std::string(buf));
}
} // namespace std

// GLIBCXX_3.4.29: __throw_bad_array_new_length (GCC 11+)
namespace std {
void __throw_bad_array_new_length()
    __attribute__((noreturn, weak));
void __throw_bad_array_new_length() {
  throw std::bad_alloc();
}
} // namespace std

// GLIBCXX_3.4.32: ios_base_library_init (GCC 12+)
// This is an init function generated by newer GCC for ios_base initialization.
namespace std {
void ios_base_library_init() __attribute__((weak));
void ios_base_library_init() {}
} // namespace std

#endif // _SHARE
